### PR TITLE
Fixes spelling error of ICNP

### PR DESCRIPTION
**Pull request by hlapp**
I would assume that ICNB is a spelling error of ICNP that was subsequently propagated through copy&paste? That's assuming that it's not a misspelling of ICBN, because it seems that has become ICN.

### CODE REVIEW

**Comment by mjy** [comment]
@proceps can you confirm?  Remarkably there "official" acronym for these things is *very* hard to figure out.

**Comment by mjy** [comment]
@proceps This reminds me that this might have consequences for corresponding constant labels in TaxonWorks (and that we need a unit test to validate that we maintain the linkages properly).

**Comment by proceps** [comment]
Bacterial code changed it name to the International Code of Nomenclature of Prokaryotes (so ICNB > ICNP)
I changed all the Constants in TW (and tests).

**Comment by mjy** [comment]
@proceps 'ICNB > ICNP' means use "ICNP", right?

**Comment by proceps** [comment]
Yes ICNP is the right name of the code now

**Pull request merged**
